### ISSUE TITLE
Any future?

### ISSUE THREAD

**Issue by dumblob** [cheery/texopic#1]
Any plans to further develop & maintain Texopic?

I'm thinking of making Texopic a bit more powerful by providing means to define own macros specific to the given in-Texopic-written document. I don't care whether it'll be a section `#def{mynewshinymacro}...#fed` with `...` being a pure Python code which'll get injected into the Python Texopic generator or whether Texopic will define own microlanguage to use in the `#def ... #fed` block.

I really just want to link the document I'm writing with the (presumably non-portable & document-specific) extension I want to use in the document.

**Comment by cheery** [comment]
No plans for texopic format.

I don't mind about changes either though.

to 10. kesäk. 2021 klo 10.37 dumblob ***@***.***> kirjoitti:

**Comment by dumblob** [comment]
Ok. Sounds like an end to the Texopic markup :wink:. Closing then.
